services:
  php_test:
    build:
      context: .
      target: frankenphp_dev
    volumes:
      - ./:/app
      - ./frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./frankenphp/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
      - ./supervisor/supervisord.test.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
      TRUSTED_HOSTS: ${TRUSTED_HOSTS:-^$${SERVER_NAME:-example\.com|localhost}|php$$}
      MERCURE_URL: ${CADDY_MERCURE_URL:-http://php/.well-known/mercure}
      MERCURE_PUBLIC_URL: ${CADDY_MERCURE_PUBLIC_URL:-https://$${SERVER_NAME:-localhost}/.well-known/mercure}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MESSENGER_TRANSPORT_DSN: redis://redis_test/messages
      APP_ENV: test
      DATABASE_URL: mysql://${MYSQL_USER:-app_test}:${MYSQL_PASSWORD:-app_test}@database_test:3306/${MYSQL_DATABASE:-app_test}?serverVersion=${MYSQL_VERSION:-8}&charset=${MYSQL_CHARSET:-utf8mb4}
    extra_hosts:
      - host.docker.internal:host-gateway
    tty: true
    depends_on:
      database_test:
        condition: service_healthy

  database_test:
    image: mysql:8
    environment:
      MYSQL_DATABASE: app_test
      MYSQL_USER: app_test
      MYSQL_PASSWORD: app_test
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_test:/var/lib/mysql:rw
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
      start_period: 60s
      
  redis_test:
    image: redis:alpine
  
volumes:
  caddy_data:
  caddy_config:
  mysql_test:
